spring:
  application:
    name: sms-flow
  datasource:
    password: "docker"
    url: "jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres"
    username: "postgres.ruexpbcygjdotksrkzbn"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  mail:
    host: "pro3.mail.ovh.net"
    port: 587
    username: "kontakt@tempowaiter.pl"
    password: "kWy681@t"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

apiKeys:
  tpaySandbox:
    clientId: "01HZ25YZ3TQS3D322DEXK047V3-01HZ2628AYDGGVG02R6Z8SRA8N"
    secret: "ee731d7384efba4c6f5b531940abef1d5d1e0225c7af70847d3c994c60a0a33b"
  tpay-prod:
    clientId: "01J00HYVAP53RTHXGYWTX9SZTR-01J03AKNB1348WM02F96ATEPQT"
    secret: "4839902a29a85c34c4bd3552cb3995d9dd84f69f1d52f4641fd322ddba6c7334"
  smsPlanet:
    secret: "tVmSO65Wdfeca35eed8c4127a2633fc00e9715df"
  shopify:
    access: "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"